# Generated by Django 2.1.7 on 2019-02-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
