# Generated by Django 2.1.7 on 2019-03-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_tile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='winner',
            name='highest_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Game'),
        ),
    ]
