# Generated by Django 2.1.7 on 2019-02-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190227_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
