# Generated by Django 2.1.5 on 2019-02-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190223_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('saved_scores', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SaveGame',
        ),
    ]
