# Generated by Django 2.1.5 on 2019-02-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190223_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Person')),
            ],
        ),
    ]
