# Generated by Django 2.1.5 on 2019-02-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game'),
        ('game', '0004_auto_20190227_1607'),
    ]

    operations = [
    ]
